/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blubee_bluengine_jniOpenGL_BLU20 */

#ifndef _Included_com_blubee_bluengine_jniOpenGL_BLU20
#define _Included_com_blubee_bluengine_jniOpenGL_BLU20
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blubee_bluengine_jniOpenGL_BLU20
 * Method:    glDrawElements
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_blubee_bluengine_jniOpenGL_BLU20_glDrawElements
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_blubee_bluengine_jniOpenGL_BLU20
 * Method:    glVertexAttribPointer
 * Signature: (IIIZII)V
 */
JNIEXPORT void JNICALL Java_com_blubee_bluengine_jniOpenGL_BLU20_glVertexAttribPointer
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
